spring:
  cloud:
    config:
      server:
        git:
          uri: ${your-git-repository-uri}
          username: ${your-git-repository-username}
          password: ${your-git-repository-password-or-token}

# Reference: https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.1.4.RELEASE/single/spring-cloud-config.html#_authentication
