spring:
  cloud:
    config:
      server:
        git:
          uri: ${your-public-git-repository-uri}

# Reference: https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.1.4.RELEASE/single/spring-cloud-config.html#_git_backend
