name: build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build java-8-sample
      run: mvn -B package -D skipTests -f java-8-sample/pom.xml
    - name: Build java-11-sample
      run: mvn -B package -D skipTests -f java-11-sample/pom.xml
    - name: Build hystrix-turbine-sample
      run: mvn -B package -D skipTests -f hystrix-turbine-sample/user-service/pom.xml
